import type { KnipConfig } from 'knip';

const config: KnipConfig = {
  ignoreDependencies: [
    '@axe-core/playwright',
    '@vitest/coverage-v8',
    'autoprefixer',
    'axe-playwright',
    'baseline-browser-mapping',
    'postcss',
    '@googleapis/sheets',
    '@types/dompurify',
    '@types/recharts',
    '@playwright/test',
    '@radix-ui/react-alert-dialog',
    '@radix-ui/react-checkbox',
    '@radix-ui/react-label',
    '@radix-ui/react-select',
    '@radix-ui/react-tabs',
    '@radix-ui/react-tooltip',
    'next-themes',
    'sonner',
    'tailwindcss-animate',
    'habit-hooks',
    'tailwindcss',
  ],

  ignoreFiles: [
    'src/pwa.d.ts',
    'src/components/ui/Checkbox.tsx',
    'src/components/ui/Label.tsx',
    'src/components/ui/Sheet.tsx',
    'src/components/ui/Sonner.tsx',
    'src/components/ui/Tabs.tsx',
    'src/components/ui/Tooltip.tsx',
    'src/components/ui/index.ts',
  ],

  ignoreIssues: {
    'src/components/ui/Table.tsx': ['exports'],
    'src/tests/helpers/mergeDataHelpers.ts': ['exports'],
    'src/utils/applications.ts': ['exports'],
    'src/utils/csv.ts': ['exports'],
    'src/utils/googleSheets.ts': ['exports'],
    'src/utils/localStorage.ts': ['exports'],
    'src/components/Alert.tsx': ['types'],
    'src/components/ui/Input.tsx': ['types'],
    'src/components/ui/Select.tsx': ['types'],
    'src/components/ui/Separator.tsx': ['types'],
    'src/types/preferences.ts': ['types'],
    'src/components/AuthModals.tsx': ['exports'],
    'src/components/GDPRCookieBanner.tsx': ['exports'],
    'src/components/OnboardingWizard.tsx': ['exports'],
    'src/storage/auth.ts': ['exports'],
    'src/components/MatchBreakdownModal.tsx': ['exports'],
    'src/components/MatchScoreBadge.tsx': ['exports'],
    'src/components/ProfileSetupModal.tsx': ['exports'],
    'src/components/RecommendationPanel.tsx': ['exports'],
    'src/components/settings/MatchingSettings.tsx': ['exports'],
    'src/storage/matching.ts': ['exports'],
    'src/utils/geminiJobScoring.ts': ['exports'],
    'src/utils/geminiProfile.ts': ['exports'],
    'src/seo/index.ts': ['exports', 'types'],
    'src/utils/constants.ts': ['exports'],
    'src/components/ui/Badge.tsx': ['exports'],
    'src/components/ui/Button.tsx': ['exports', 'types'],
    'src/components/ui/Dialog.tsx': ['exports'],
    'src/components/ui/DropdownMenu.tsx': ['exports'],
    'src/components/ui/Textarea.tsx': ['types'],
    'src/components/profileSetupReducer.ts': ['types'],
    'src/components/emailScanReducer.ts': ['types'],
    'src/components/ui/Checkbox.tsx': ['exports'],
    'src/components/ui/Label.tsx': ['exports'],
    'src/components/ui/Sheet.tsx': ['exports'],
    'src/components/ui/Sonner.tsx': ['exports'],
    'src/components/ui/Tabs.tsx': ['exports'],
    'src/components/ui/Tooltip.tsx': ['exports'],
    'src/components/ui/index.ts': ['exports'],
    'src/components/BasicDetailsFields.tsx': ['exports'],
    'src/components/GeminiKeyFormFields.tsx': ['exports'],
    'src/components/ManualInputTab.tsx': ['exports'],
    'src/components/ScanAuthGate.tsx': ['exports'],
    'src/components/ScanResults.tsx': ['exports'],
    'src/components/ManualProcessingPanel.tsx': ['exports'],
    'src/components/settings/CloudAccountSection.tsx': ['exports'],
    'src/components/settings/SettingsSectionHeader.tsx': ['exports'],
    'src/components/settings/SettingsSidebar.tsx': ['exports'],
    'src/components/SheetsAuthGate.tsx': ['exports'],
    'src/components/SheetSelectInput.tsx': ['exports'],
    'src/components/SourceFields.tsx': ['exports'],
    'src/components/TrackingFields.tsx': ['exports'],
  },

  project: ['src/**/*.{ts,tsx}'],

  entry: ['index.html'],
};

export default config;
