#!/bin/bash
#
# Orphan version sweep — finds stale quoted version literals in the repo.
#
# Wraps `rg` to scan every project-tracked file for any literal occurrence
# of the current package.json version formatted as `"<version>"` (i.e. the
# JSON-quoted form used in `package.json`, package-lock.json keys,
# telemetry constants, etc.). Files/paths that legitimately reference
# past or unrelated versions are excluded per the AGENTS.md Versioning
# rule's allow-list:
#
#   - CHANGELOG.md             (immutable historical release headings)
#   - package-lock.json        (third-party dep versions, unrelated to ours)
#   - api/composer.lock        (same)
#   - api/vendor/**            (generated composer tree)
#   - audit/                   (audit report + JSON regenerated by `audit/audit.cjs` when a release is cut; the version it carries is the audited subject, not an orphan)
#   - package.json             (the source-of-truth version itself; without this exclude, every release would self-report an orphan against its own root)
#   - node_modules             (generated npm tree)
#   - .git, .jules             (VCS + AI memory, not user-facing)
#
# Usage:
#   scripts/check-orphans.sh <version>
#
# Exit codes:
#   0  — script ran (regardless of orphan count; the body indicates state)
#   2  — missing version argument
#   3+ — rg's own exit code, propagated for real I/O / permission errors
#
# Output (stdout, ready for a GitHub Issue body):
#   When clean: "_No orphans found._"
#   Otherwise:  a Markdown table
#               | File | Line | Content |
#               |---|---|---|
#               | <path> | <lineno> | `<content>` |
#
# Cron-friendly: idempotent, no side effects, deterministic output for
# the same input.
#
# Implementation notes (worth preserving across refactors):
#
#   1. rg runs in fixed-string mode (`-F`) so the version pattern is
#      matched byte-for-byte — no regex dot-escaping, no `\b` footgun
#      between word and non-word characters around the quote boundary.
#
#   2. The `--` separator sits AFTER every `-g` flag and BEFORE the
#      PATTERN positional arg. If `--` is moved UPSTREAM of any `-g`,
#      rg treats `-g '!foo'` as `(search-path: -g, search-path: !foo)`
#      which never exists, so rg exits 2 with `No such file or directory`.
#      This bug cost one round of CI runs; preserved here so the next
#      refactor doesn't reintroduce it.
#
#   3. The trailing `.` is mandatory. rg defaults to scanning the
#      current directory when run from an interactive TTY, but in a
#      non-interactive context (CI runners, cron jobs, command
#      substitution inside `$()`) it silently falls back to reading
#      stdin — which is always empty when the workflow doesn't pipe
#      anything in, leading to "no matches" for files that ARE present.

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

if [ $# -lt 1 ]; then
  echo "usage: $0 <version>" >&2
  exit 2
fi

VERSION="$1"

# Pattern: literally `"<version>"` (quotes both sides). In fixed-string
# mode this matches only the JSON-encoded form, not bare `2.5.0` in
# prose; package.json sibling keys, etc. Tracked CHANGELOG entries
# are already excluded by the -g glob below.
PATTERN="\"${VERSION}\""

# rg exit codes: 0 = matches, 1 = no matches, 2+ = hard error (I/O,
# permission, broken symlink, invalid pattern). We deliberately treat
# "no matches" (exit 1) as a clean (orphan-free) state and return 0 so
# the GitHub Action can publish a green status. Hard errors propagate
# verbatim so the workflow surfaces a real failure rather than
# silently logging "no orphans" against a broken fs.
MATCHES="$(rg -F -n \
    -g '!node_modules' \
    -g '!api/vendor' \
    -g '!package-lock.json' \
    -g '!api/composer.lock' \
    -g '!CHANGELOG.md' \
    -g '!audit' \
    -g '!package.json' \
    -g '!.git' \
    -g '!.jules' \
    -- "$PATTERN" \
    . 2>/dev/null)"
rg_exit=$?

if [ "$rg_exit" -ge 2 ]; then
  echo "::error::rg exited with code $rg_exit (permission denied / broken symlink / invalid path)" >&2
  exit "$rg_exit"
fi

if [ "$rg_exit" -eq 1 ] || [ -z "$MATCHES" ]; then
  echo "_No orphans found._"
  exit 0
fi

# rg -n prints "<path>:<line>:<content>". Content may legitimately
# contain colons (rare in this repo but possible in URL-encoded paths
# or window.location-style strings), so we deliberately preserve only
# the first two colons as separators and re-join the rest.
echo "| File | Line | Content |"
echo "|---|---|---|"
echo "$MATCHES" | awk -F: '
  {
    file = $1
    line = $2
    content = $3
    for (i = 4; i <= NF; i++) content = content ":" $i
    printf "| %s | %s | `%s` |\n", file, line, content
  }
'
exit 0
