// src/setupTests.ts
import React from 'react';
import '@testing-library/jest-dom';
import './tests/google-oauth-mock';
import { vi } from 'vitest';

declare global {
  // Flag picked up in components to avoid real network calls while testing.
  var __TEST__: boolean | undefined;
}

const globalWithTestFlag = globalThis as typeof globalThis & { __TEST__?: boolean };
globalWithTestFlag.__TEST__ = true;

// Mock react-i18next
vi.mock('react-i18next', () => {
  const translations: Record<string, string> = {
  "landing.heroTitle": "Master Your Job Search",
  "landing.heroSubtitle": "The ultimate tool to track applications, manage interviews, and land your dream job.",
  "landing.getStarted": "Get Started",
  "landing.features": "Features",
  "landing.feature1Title": "Multiple Perspectives",
  "landing.feature1Desc": "Visualize your applications through Table, Kanban, Timeline, and Calendar views.",
  "landing.feature2Title": "Chrome Extension",
  "landing.feature2Desc": "Capture job details directly from LinkedIn, Greenhouse, and more with a single click.",
  "landing.feature3Title": "Powerful Insights",
  "landing.feature3Desc": "Track your funnel, analyze interview performance, and see where you're succeeding.",
  "landing.feature4Title": "Google Sheets Sync",
  "landing.feature4Desc": "Keep your data safe and synced with your own Google Sheets for easy backup and sharing.",
  "landing.roadmap": "What's Coming Next",
  "landing.ready": "Ready to accelerate your career?",
  "landing.enterApp": "Enter Application",
  "landing.footer": "\u00a9 2025 Job Application Tracker. Master your career path.",
  "common.footer.vibecoded": "Vibecoded with love \u2764\ufe0f by godie with cursor v{{version}} ({{year}})",
  "common.footer.terms": "Terms of Service",
  "common.footer.privacy": "Privacy",
  "common.loading": "Loading...",
  "common.loginSuccess": "Successful Login with Google!",
  "common.loginError": "Login successful but failed to store credentials securely.",
  "common.loginFailed": "Failed to login with Google. Please try again.",
  "common.logoutSuccess": "Logged out successfully!",
  "common.logoutPartial": "Logged out (some credentials may remain on server).",
  "common.logout": "Logout",
  "common.loginWithGoogle": "Login with Google",
  "common.save": "Save",
  "common.cancel": "Cancel",
  "common.delete": "Delete",
  "common.edit": "Edit",
  "common.add": "Add",
  "common.actions": "Actions",
  "common.status": "Status",
  "common.company": "Company",
  "common.position": "Position",
  "common.date": "Date",
  "common.example": "Example",
  "common.anyAport": "Any contribution is greatly appreciated! \u2764\ufe0f",
  "common.next": "Next",
  "common.previous": "Previous",
  "common.goToPage": "Go to page {{page}}",
  "common.status_types.completed": "Completed",
  "common.status_types.scheduled": "Scheduled",
  "common.status_types.cancelled": "Cancelled",
  "common.status_types.pending": "Pending",
  "statuses.applied": "Applied",
  "statuses.interviewing": "Interviewing",
  "statuses.offer": "Offer",
  "statuses.rejected": "Rejected",
  "statuses.withdrawn": "Withdrawn",
  "statuses.hold": "Hold",
  "fields.position": "Position",
  "fields.company": "Company",
  "fields.status": "Status",
  "fields.applicationDate": "Application Date",
  "fields.timeline": "Timeline",
  "fields.notes": "Notes",
  "fields.link": "Link",
  "fields.platform": "Platform",
  "fields.salary": "Salary",
  "fields.contactName": "Contact",
  "fields.followUpDate": "Follow Up",
  "nav.applications": "Applications",
  "nav.opportunities": "Opportunities",
  "nav.settings": "Settings",
  "nav.insights": "Insights",
  "nav.support": "Support",
  "nav.about": "About",
  "home.pipeline": "Application Pipeline",
  "home.addEntry": "+ Add Entry",
  "home.showing": "Showing <span class=\"font-semibold text-gray-700 dark:text-gray-300\">{{count}}</span> of {{total}} applications",
  "home.noApplications": "Use the \"+ Add Entry\" button to start tracking your applications!",
  "home.metrics.applications": "Applications",
  "home.metrics.interviews": "Interviews",
  "home.metrics.offers": "Offers",
  "home.deleteConfirm.title": "Delete Application",
  "home.deleteConfirm.titleFor": "Delete application for {{position}} at {{company}}",
  "home.deleteConfirm.message": "Are you sure you want to delete the application for \"{{position}}\" at {{company}}? This action will mark it as deleted.",
  "home.success.captured": "New job opportunity captured from LinkedIn!",
  "home.success.deleted": "Application \"{{position}}\" at {{company}} has been marked as deleted.",
  "support.title": "Community and Support",
  "support.subtitle": "Help us improve the tool or support development.",
  "support.donations": "Donations",
  "support.donationsDesc": "If this tool has been useful to you and you want to support its maintenance and new features, consider buying us a coffee.",
  "support.buyMeACoffee": "Buy Me a Coffee",
  "support.suggestions": "Suggestions",
  "support.suggestionsDesc": "Share your ideas directly with us. Every submission goes into a secure queue so we can review it later.",
  "support.suggestionType": "Suggestion type",
  "support.explanation": "Explanation",
  "support.explanationPlaceholder": "Tell us more about your idea or the problem you found...",
  "support.submit": "Send suggestion",
  "support.submitting": "Sending...",
  "support.submitSuccess": "Thanks! Your suggestion was sent.",
  "support.submitError": "We couldn't send your suggestion. Please try again in a moment.",
  "support.submitInfo": "Suggestions are stored on a lightweight PHP + SQLite queue that we download and process manually.",
  "support.captchaLabel": "Captcha",
  "support.captchaDesc": "Enter the digits displayed to prove you're human.",
  "support.captchaRefresh": "New code",
  "support.captchaPlaceholder": "Enter digits",
  "support.captchaLoading": "Loading...",
  "support.captchaRequired": "Please complete the captcha before sending your suggestion.",
  "support.captchaError": "We couldn't generate the captcha. Refresh and try again.",
  "support.explanationRequired": "Please describe your idea before sending it.",
  "support.errorGeneric": "Something went wrong. Please try again later.",
  "support.howItWorks": "How does it work?",
  "support.howItWorksDesc": "We now store suggestions in a lightweight server queue. Each submission uses a short <strong>numeric captcha</strong> to keep bots away so the server doesn't get flooded.",
  "support.types.ui-ux": "UI/UX",
  "support.types.functionality": "Functionality",
  "support.types.bug": "Bug",
  "support.types.feature": "Feature",
  "support.types.improvements": "Improvements",
  "support.promptPrefix": "Hi Jules, I have a suggestion for the Job Application Tracker.",
  "support.promptType": "Type",
  "support.promptExplanation": "Explanation",
  "support.copied": "Prompt copied to clipboard! You can send it to me now.",
  "settings.title": "Settings",
  "settings.subtitle": "Customize your application tracking experience. All changes are saved locally in your browser.",
  "settings.sections.fields": "Table Fields",
  "settings.sections.view": "Default View",
  "settings.sections.date": "Date Format",
  "settings.sections.dateDesc": "Choose how dates should be displayed throughout the application.",
  "settings.sections.custom": "Custom Fields",
  "settings.sections.interviewing": "Interview Events",
  "settings.saveChanges": "Save Changes",
  "settings.resetDefault": "Reset to Default",
  "settings.unsavedChanges": "You have unsaved changes",
  "settings.fields.title": "Application Fields Configuration",
  "settings.fields.desc": "Choose which columns you want to see in your Applications table and adjust their order.",
  "settings.fields.required": "Required core field",
  "settings.fields.optional": "Optional field",
  "settings.fields.custom": "Custom",
  "settings.view.title": "Default View",
  "settings.view.desc": "Choose which view should be displayed when you open the Applications page.",
  "settings.view.table": "Enhanced table with filters",
  "settings.view.timeline": "Chronological interview flow",
  "settings.view.kanban": "Board view grouped by status",
  "settings.view.calendar": "Monthly calendar of interviews",
  "settings.custom.title": "Custom Fields",
  "settings.custom.desc": "Create your own fields to track additional information about your applications.",
  "settings.custom.add": "Add New Custom Field",
  "settings.custom.edit": "Edit Custom Field",
  "settings.custom.label": "Field Label *",
  "settings.custom.type": "Field Type *",
  "settings.custom.options": "Options (one per line) *",
  "settings.custom.optionsDesc": "Enter one option per line. These will appear as dropdown options.",
  "settings.custom.required": "Required field",
  "settings.custom.update": "Update Field",
  "settings.custom.addField": "Add Field",
  "settings.custom.noCustom": "No custom fields yet. Create one above to get started!",
  "settings.custom.types.text": "Text",
  "settings.custom.types.date": "Date",
  "settings.custom.types.number": "Number",
  "settings.custom.types.select": "Select (Dropdown)",
  "settings.custom.types.checkbox": "Checkbox",
  "settings.custom.types.url": "URL",
  "settings.interviewing.title": "Interview Events",
  "settings.interviewing.desc": "Manage custom interview event types that will be available when creating timeline events.",
  "settings.interviewing.add": "Add New Interview Event",
  "settings.interviewing.edit": "Edit Interview Event",
  "settings.interviewing.label": "Event Label *",
  "settings.interviewing.update": "Update Event",
  "settings.interviewing.addEvent": "Add Event",
  "settings.interviewing.noEvents": "No custom interview events yet. Create one above to get started!",
  "settings.success": "Settings saved successfully!",
  "insights.title": "Insights",
  "insights.applicationsByStatus": "Applications by Status",
  "insights.totalApplications": "Total Applications",
  "insights.totalInterviews": "Total Interviews",
  "insights.rejectedApplications": "Rejected Applications",
  "insights.rejectionPercentage": "Rejection Percentage",
  "insights.interviewsByStatus": "Interviews by Application Status",
  "insights.interviewsByType": "Interviews by Type",
  "insights.interviewTypes.screener_call": "Screener Call",
  "insights.interviewTypes.first_contact": "First Contact",
  "insights.interviewTypes.technical_interview": "Technical Interview",
  "insights.interviewTypes.code_challenge": "Code Challenge",
  "insights.interviewTypes.live_coding": "Live Coding",
  "insights.interviewTypes.hiring_manager": "Hiring Manager",
  "insights.interviewTypes.system_design": "System Design",
  "insights.interviewTypes.cultural_fit": "Cultural Fit",
  "insights.interviewTypes.final_round": "Final Round",
  "insights.interviewTypes.application_submitted": "Application Submitted",
  "insights.interviewTypes.offer": "Offer",
  "insights.interviewTypes.rejected": "Rejected",
  "insights.interviewTypes.withdrawn": "Withdrawn",
  "insights.interviewTypes.custom": "Custom",
  "opportunities.title": "Interesting Opportunities",
  "opportunities.subtitle": "Job opportunities captured from LinkedIn or added manually. Click \"Apply\" to convert them into applications.",
  "opportunities.addOpportunity": "+ Add Opportunity",
  "opportunities.noOpportunities": "No opportunities yet",
  "opportunities.noOpportunitiesDesc": "Install the Chrome extension to capture job opportunities from LinkedIn.",
  "opportunities.searchPlaceholder": "Search opportunities...",
  "opportunities.showing": "Showing {{count}} of {{total}} opportunities",
  "opportunities.table.position": "Position",
  "opportunities.table.company": "Company",
  "opportunities.table.location": "Location",
  "opportunities.table.jobType": "Job Type",
  "opportunities.table.posted": "Posted",
  "opportunities.table.captured": "Captured",
  "opportunities.table.actions": "Actions",
  "opportunities.actions.view": "View",
  "opportunities.actions.apply": "Apply",
  "opportunities.deleteConfirm.title": "Delete Opportunity",
  "opportunities.deleteConfirm.message": "Are you sure you want to delete \"{{position}}\" at {{company}}?",
  "opportunities.success.addedToApps": "\"{{position}}\" at {{company}} has been added to your applications!",
  "opportunities.success.deleted": "Opportunity \"{{position}}\" has been deleted.",
  "opportunities.success.added": "Opportunity \"{{position}}\" at {{company}} has been added!",
  "opportunities.success.convertError": "Failed to convert opportunity to application. Please try again.",
  "opportunities.success.addError": "Failed to add opportunity. Please try again.",
  "filters.search": "Search",
  "filters.searchPlaceholder": "Search by position, company, notes...",
  "filters.status": "Status",
  "filters.include": "Include",
  "filters.includeWithCount": "\u2713 Include ({{count}})",
  "filters.exclude": "Exclude",
  "filters.excludeWithCount": "\u2717 Exclude ({{count}})",
  "filters.clearStatus": "Clear status filters",
  "filters.platform": "Platform",
  "filters.all": "All",
  "filters.from": "From",
  "filters.to": "To",
  "filters.clear": "Clear",
  "views.table": "Table",
  "views.timeline": "Timeline",
  "views.kanban": "Kanban",
  "views.calendar": "Calendar",
  "kanban.noApplications": "No applications yet.",
  "kanban.startAdding": "Start adding entries to see them organized here.",
  "kanban.noAppsInStage": "No applications in this stage.",
  "kanban.applied": "Applied {{date}}",
  "kanban.timeline": "Timeline",
  "kanban.more": "+{{count}} more",
  "timeline.noApplications": "No applications yet.",
  "timeline.startAdding": "Start adding entries to see the interview timeline.",
  "timeline.nextEvent": "Next: {{date}}",
  "timeline.noEvents": "No timeline events yet.",
  "timeline.expand": "Expand application details",
  "timeline.collapse": "Collapse application details",
  "calendar.title": "Calendar",
  "calendar.today": "Today",
  "calendar.noApplications": "No applications yet. Add some to see them on the calendar.",
  "calendar.relative.today": "Today",
  "calendar.relative.tomorrow": "Tomorrow",
  "calendar.relative.yesterday": "Yesterday",
  "calendar.relative.inDays": "in {{count}} days",
  "calendar.relative.daysAgo": "{{count}} days ago",
  "calendar.weekdays.Sun": "Sun",
  "calendar.weekdays.Mon": "Mon",
  "calendar.weekdays.Tue": "Tue",
  "calendar.weekdays.Wed": "Wed",
  "calendar.weekdays.Thu": "Thu",
  "calendar.weekdays.Fri": "Fri",
  "calendar.weekdays.Sat": "Sat",
  "sheets.title": "Google Sheets Integration",
  "sheets.loginRequired": "<strong>Google Sheets Sync:</strong> Please log in with Google to enable spreadsheet synchronization.",
  "sheets.loginFirst": "Please log in with Google first",
  "sheets.status": "Status",
  "sheets.error": "Sync Error",
  "sheets.synced": "Synced {{time}}",
  "sheets.notSynced": "Not synced yet",
  "sheets.openSheet": "Open Spreadsheet \u2192",
  "sheets.changeSheet": "Change Sheet",
  "sheets.createSheetDesc": "Create a Google Sheet to sync your job applications.",
  "sheets.createSheet": "Create Sheet",
  "sheets.creating": "Creating...",
  "sheets.selectExisting": "Select Existing",
  "sheets.syncNow": "Sync Now",
  "sheets.syncing": "Syncing...",
  "sheets.spreadsheetCreated": "Spreadsheet created! Opening in new tab...",
  "sheets.syncSuccess": "Successfully synced {{count}} application to Google Sheets!",
  "sheets.syncSuccess_plural": "Successfully synced {{count}} applications to Google Sheets!",
  "sheets.syncError": "Failed to sync data",
  "sheets.noSpreadsheet": "No spreadsheet found. Please create one first.",
  "sheets.selectTitle": "Select Existing Spreadsheet",
  "sheets.selectDesc": "Enter the spreadsheet ID or full URL from Google Sheets",
  "sheets.placeholder": "Spreadsheet ID or URL",
  "sheets.set": "Set",
  "sheets.setting": "Setting...",
  "sheets.selectSuccess": "Spreadsheet \"{{title}}\" selected successfully!",
  "sheets.setError": "Failed to set spreadsheet",
  "form.addTitle": "Add New Job Application",
  "form.addOpportunityTitle": "Add New Opportunity",
  "form.editTitle": "Edit Application",
  "form.basicDetails": "Basic Details",
  "form.trackingTimeline": "Tracking & Timeline",
  "form.sourceContact": "Source & Contact",
  "form.position": "Position *",
  "form.company": "Company *",
  "form.applicationDate": "Application Date *",
  "form.status": "Status *",
  "form.salary": "Salary / Range",
  "form.interviewDate": "Interview Date",
  "form.followUpDate": "Follow-up Date",
  "form.link": "Link (Job Posting)",
  "form.platform": "Platform",
  "form.contactName": "Contact Name (Recruiter/Hiring Manager)",
  "form.notes": "Notes",
  "form.description": "Description",
  "form.postedDate": "Posted Date",
  "form.saveApplication": "Save Application",
  "form.saveChanges": "Save Changes",
  "form.saveOpportunity": "Save Opportunity",
  "form.validation.positionRequired": "Position is required",
  "form.validation.companyRequired": "Company is required",
  "form.validation.linkRequired": "Link is required",
  "form.validation.invalidUrl": "Please enter a valid URL",
  "form.platforms.LinkedIn": "LinkedIn",
  "form.platforms.Indeed": "Indeed",
  "form.platforms.Company Website": "Company Website",
  "form.platforms.Referral": "Referral",
  "form.platforms.Other": "Other",
  "fields.role": "Position"
};

  type TranslationValues = Record<string, string | number | undefined>;

  return {
    useTranslation: () => ({
      t: (key: string, options?: TranslationValues) => {
        let result = translations[key] || key;
        if (options) {
          if (options.count !== undefined) {
             if (key === 'home.metrics.applications') return options.count === 1 ? 'Application' : 'Applications';
             if (key === 'home.metrics.interviews') return options.count === 1 ? 'Interview' : 'Interviews';
             if (key === 'home.metrics.offers') return options.count === 1 ? 'Offer' : 'Offers';
             if (key === 'home.showing') return options.count === 1 ? `Showing 1 of ${options.total} applications` : `Showing ${options.count} of ${options.total} applications`;
             if (key === 'opportunities.showing') return options.count === 1 ? `Showing 1 of ${options.total} opportunities` : `Showing ${options.count} of ${options.total} opportunities`;
          }
          Object.keys(options).forEach((optKey) => {
            const value = options[optKey];
            result = result.replace('{{' + optKey + '}}', value !== undefined ? String(value) : '');
          });
        }
        return result;
      },
      i18n: {
        changeLanguage: () => Promise.resolve(),
        language: 'en',
      },
    }),
    initReactI18next: {
      type: '3rdParty',
      init: () => {},
    },
    Trans: ({
      i18nKey,
      values,
      children,
    }: {
      i18nKey: string;
      values?: TranslationValues;
      children?: React.ReactNode;
    }) => {
      let result = translations[i18nKey] || i18nKey || '';
      if (values) {
        Object.keys(values).forEach((optKey) => {
          const value = values[optKey];
          result = result.replace('{{' + optKey + '}}', value !== undefined ? String(value) : '');
        });
      }

      if (i18nKey === 'home.showing') {
        return React.createElement('span', null, result);
      }
      if (i18nKey === 'support.howItWorksDesc' || i18nKey === 'sheets.loginRequired' || i18nKey === 'common.footer.vibecoded') {
          return React.createElement('span', { dangerouslySetInnerHTML: { __html: result || children } });
      }

      if (result && result !== i18nKey) return result;
      return children;
    },
  };
});
